### ISSUE TITLE
Category Buttons Not Filtering News

### ISSUE THREAD

**Issue by cjstyles6** [cjstyles6/News-Website#1]
**Category Buttons Not Filtering News**
****
**Description**
The category buttons (general, business, etc) are not properly filtering the news results when clicked. Instead of showing news for that specific category, it is showing the same results as the keyword search.

Steps to reproduce:

1. Load page
2. Click on a category button like "Business"
3. Notice the news results are not filtered and show the same results as the keyword search

**Expected Behavior**
When a category button is clicked, the news results should be filtered to only show articles related to that category.

For example, clicking "Business" should show top business news.

**Actual Behavior**
The category buttons do not filter the results. The news articles remain the same as the keyword search.

**Comment by sol-jr** [comment]
Hi 👋 I would like to work this issue please assign it to me. Thank you!

**Comment by cjstyles6** [comment]
@Dwayne-B you can work on the issue now
